define({
  "viz_settings": "Configurações de Visualização",
  "viz_type": "Tipo de Visualização",
  "max_height": "Altura Máxima de Símbolo (em metros)",
  "max_width": "Largura Máxima de Símbolo (em metros)",
  "interval": "Intervalo (milissegundos)",
  "show_percent": "Exibir valores como percentagem de todos os valores",
  "show_percentage_limited": "Encontra-se desativado, já que o número de registos é superior a 400.",
  "cycle_colors": "Muda Automaticamente de Cor",
  "area_extrusion": "Extrusão de Área",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Superfície de grelha",
  "jet_trail": "Jet Trail",
  "point_extrusion": "Ponto de Extrusão",
  "pulse": "Pulse",
  "layer_settings": "Configurações de Camada",
  "viz_layer": "Camada de Visualização",
  "display_field": "Exibir Campo",
  "add_field": "Adicionar Campo de Visualização",
  "field": "Campo",
  "label": "Rótulo",
  "actions": "Acções",
  "no_layers": " Nenhuma camada disponível na cena web seleccionada.",
  "viz_not_supported": "Não suportado no tipo de geometria da camada selecionada."
});