// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:builder/plugins/widget-config/WidgetSettingPage.html":'\x3cdiv class\x3d"widget-setting-page"\x3e\r\n  \x3cdiv class\x3d"section common-setting" data-dojo-attach-point\x3d"commonSettingNode"\x3e\r\n    \x3cdiv class\x3d"basic"\x3e\r\n      \x3cdiv class\x3d"icon jimu-float-leading"\x3e\r\n        \x3cimg class\x3d"real-icon"  data-dojo-attach-point\x3d"iconNode"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv class\x3d"right jimu-float-trailing jimu-leading-margin1"\x3e\r\n        \x3cinput data-dojo-type\x3d"dijit/form/ValidationTextBox" data-dojo-attach-point\x3d"labelNode" placeholder\x3d"${nls.widgetLabel}" required\x3d"true" class\x3d"widget-setting-input"\x3e\r\n        \x3cdiv class\x3d"right-foot" data-dojo-attach-point\x3d"rightFooterNode"\x3e\r\n          \x3cdiv class\x3d"image-container"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"imageChooserPlaceholder"\x3e\x3c/div\x3e\r\n            \x3c!-- \x3cspan nowrap class\x3d"change-icon" data-dojo-attach-point\x3d"changeNode"\x3e${nls.changeIcon}\x3c/span\x3e --\x3e\r\n            \x3ca class\x3d"help-link jimu-float-trailing" target\x3d"_blank" data-dojo-attach-point\x3d"helpNode"\x3e${nls.more}\x3c/a\x3e\r\n          \x3c/div\x3e\r\n        \x3c/div\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"layout"\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"section widget-setting" data-dojo-attach-point\x3d"widgetSettingNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/_base/config dojo/Deferred dojo/request dojo/topic dojo/aspect dojo/on dojo/mouse dojo/query dojo/string dojo/NodeList-dom dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./WidgetSettingPage.html ./WidgetDefaultSettingPage jimu/utils jimu/WidgetManager jimu/portalUrlUtils jimu/portalUtils jimu/dijit/ViewStack jimu/dijit/ImageChooser jimu/dijit/LoadingIndicator jimu/dijit/Message dijit/form/CheckBox esri/request".split(" "),
function(t,c,b,H,k,u,l,v,I,p,J,K,w,L,x,y,z,A,B,h,q,r,M,N,f,C,D,O,E){var F="en de es fr ja ru zh-cn zh-tw zh-hk ar it ko pl pt-br pt-pt ro".split(" "),G=[],m=null;return t([x,y,z],{templateString:A,startup:function(){this.inherited(arguments);this.own(l("builder/widgethelp.json",{handleAs:"json"}).then(function(a){m=a},function(a){console.error(a)}).always(c.hitch(this,function(){this.domNode&&(this.own(p(window,"resize",c.hitch(this,this.resize))),this.init())})))},init:function(){this.loading=new C;
b.addClass(this.loading.domNode,"load-widget-setting");this.loading.placeAt(this.widgetSettingNode);this.initCommonAttr();this.initWidgetAttr();this.resize()},resize:function(){var a=b.getContentBox(this.domNode);b.setStyle(this.widgetSettingNode,{height:a.h-90+"px"})},onCancel:function(){this.onClose();this.popup.close()},onOk:function(){var a=this._checkLabelExist();if(a)return new D({message:a}),!1;this.imageChooser.imageData&&(this.setting.icon=this.imageChooser.imageData);this.setting.label=
h.stripHTML(this.labelNode.get("value"));if(this.settingDijit){a=this.settingDijit.getConfig(!0);if(!1===a)return!1;this.setting.config=a}delete this.setting.isDefaultConfig;v.publish("widgetSettingPageOk",this.setting,this.fromNode);this.onClose();this.popup.close()},_checkLabelExist:function(){var a=0,g=this.labelNode.get("value");if(""===w.trim(g))return this.nls.labelRequired;var e=h.getControllerWidgets(this.appConfig);this.appConfig.visitElement(c.hitch(this,function(d){this.setting.id!==d.id&&
d.label===g&&(0<e.length?a++:d.isOnScreen&&a++)}));return 0<a?this.nls.labelExists:""},onClose:function(){this.settingViewStack?(this.settingDijitUI.destroy(),this.settingDijitJSON.destroy(),this.settingViewStack.destroy()):this.settingDijit&&this.settingDijit.destroy()},_getHelpLink:function(a,g){var e=new u,d=null;a=a.toLowerCase();g="html"===(g||"html").toLowerCase()?"widgets2d":"widgets3d";if(window.isXT)l("/webappbuilder/help/exists",{handleAs:"json"}).then(c.hitch(this,function(b){b&&b.exists?
l("/webappbuilder/help/cxhelp.js",{handleAs:"json"}).then(c.hitch(this,function(b){var n="#";d=c.getObject("dev."+g+"."+a,!1,m);b&&b.m&&d&&b.m[d]?n="/webappbuilder/help/"+b.m[d]:d&&(n="/webappbuilder/help/"+d);e.resolve(n)}),c.hitch(this,function(a){console.warn(a);e.resolve("#")})):e.resolve("#")}),function(a){console.error(a);e.resolve("#")});else{var b=r.getPortalUrlFromLocation();if(-1<b.indexOf("arcgis.com")){var f="#",d=c.getObject("online."+g+"."+a,!1,m);"widgets3d"===g||k.locale.toLowerCase().startWith("en")||
-1<G.indexOf(a)||-1===F.indexOf(k.locale.toLowerCase())?(d&&(f="http://"+(-1<b.indexOf("maps.arcgis.com")?"doc":"docdev")+".arcgis.com/en/web-appbuilder/create-apps/"+d),e.resolve(f)):(f={url:r.getPortalSelfInfoUrl(b),content:{f:"json",culture:k.locale},handleAs:"json",callbackParamName:"callback",preventCache:!0},E(f).then(c.hitch(this,function(a){var b="#";if(a&&a.helpBase&&d)try{b=a.helpBase.split("/").slice(0,4).join("/")+"/web-appbuilder/create-apps/"+d}catch(P){b="http://doc.arcgis.com/en/web-appbuilder/create-apps/"+
d}e.resolve(b)}),c.hitch(this,function(a){console.warn(a);e.resolve("#")})))}else{var h=k.locale||"en",d=c.getObject("portal."+g+"."+a,!1,m);l(b+"portalhelp/en/website/help/cxhelp.js",{handleAs:"json"}).then(c.hitch(this,function(a){var c="#";a&&a.m&&d&&a.m[d]&&(c=b+"portalhelp/"+h+"/website/help/"+a.m[d]);e.resolve(c)}),c.hitch(this,function(a){console.warn(a);e.resolve("#")}))}}return e},initCommonAttr:function(){var a=h.processUrlInAppConfig(this.setting.icon);b.setAttr(this.iconNode,"src",a);
this.labelNode.set("value",this.setting.label);this._getHelpLink(this.setting.name,c.getObject("manifest.platform",!1,this.setting)).then(c.hitch(this,function(a){"#"!==a&&(b.setStyle(this.helpNode,"display","inline-block"),b.setAttr(this.helpNode,"href",a))}));this.imageChooser=new f({goldenWidth:24,goldenHeight:24,format:[f.GIF,f.JPEG,f.PNG],label:this.nls.changeIcon},this.imageChooserPlaceholder);b.addClass(this.imageChooser.domNode,"jimu-float-leading");!1===this.setting.inPanel&&!0===this.setting.isOnScreen&&
!0!==this.setting.closeable?(this.imageChooser.disableChooseImage(),b.setAttr(this.imageChooser.domNode,"title",this.nls.unableChangeIcon)):(this.imageChooser.enableChooseImage(),this.own(p(this.imageChooser,"imageChange",c.hitch(this,function(a){this.iconNode.src=a;this.setting.icon=a}))))},initWidgetAttr:function(){!1===this.setting.hasConfig?this.widgetSettingNode.innerHTML='\x3cdiv class\x3d"noconfig-info"\x3e'+this.nls.noConfig+"\x3c/div\x3e":q.getInstance().tryLoadWidgetConfig(this.setting).then(c.hitch(this,
function(a){this.setting.hasSettingPage?q.getInstance().loadWidgetSettingPage(this.setting).then(c.hitch(this,function(a){this.widgetSettingNode?(this.settingDijit=a,b.place(this.settingDijit.domNode,this.widgetSettingNode),this.settingDijit.startup(),this.loading.destroy(),b.setAttr(this.widgetSettingNode,"data-widget-loaded","true")):a.destroy()})):this.widgetSettingNode&&(this.settingDijit=new B({config:this.setting.config}),b.place(this.settingDijit.domNode,this.widgetSettingNode),this.settingDijit.startup(),
this.loading.destroy())}))},setAppConfig:function(a){this.appConfig=a}})});