define({
  "viz_settings": "Configurações de Visualização",
  "viz_type": "Tipo de Visualização",
  "max_height": "Altura Máxima do Símbolo (metros)",
  "max_width": "Largura Máxima do Símbolo (metros)",
  "interval": "Intervalo (milesegundos)",
  "show_percent": "Mostrar valores como porcentagem de todos os valores",
  "show_percentage_limited": "Isto é desativado já que o número de registros é maior que 400.",
  "cycle_colors": "Alterar Cores Automaticamente",
  "area_extrusion": "Extrusão de Área",
  "bounce": "Pular",
  "fireball": "Bola de Fogo",
  "grid_surface": " Superfície da Grade",
  "jet_trail": "Jet Trail",
  "point_extrusion": "Extrusão de Ponto",
  "pulse": "Pulso",
  "layer_settings": "Configurações da Camada",
  "viz_layer": "Camada de Visualização",
  "display_field": "Campo de Visualização",
  "add_field": "Adicionar Campo de Visualização",
  "field": "Campo",
  "label": "Rótulo",
  "actions": "Ações",
  "no_layers": " Nenhuma camada disponível na cena da web selecionada.",
  "viz_not_supported": "Não suportado para tipo de geometria da camada selecionada."
});