define({
  "viz_settings": "Thiết lập Trực quan hóa",
  "viz_type": "Loại Trực quan hóa",
  "max_height": "Chiều cao Ký hiệu Tối đa (mét)",
  "max_width": "Chiều rộng Ký hiệu Tối đa (mét)",
  "interval": "Khoảng thời gian (mili giây)",
  "show_percent": "Hiện giá trị dưới dạng phần trăm tất cả giá trị",
  "show_percentage_limited": "Tính năng này đã bị vô hiệu hóa do số lượng bản ghi lớn hơn 400.",
  "cycle_colors": "Tự động Đổi Màu",
  "area_extrusion": "Vùng Nhô ra",
  "bounce": "Bật lên",
  "fireball": "Cầu lửa",
  "grid_surface": " Bề mặt lưới",
  "jet_trail": "Vệt khói Máy bay",
  "point_extrusion": "Mức trồi sụt Điểm",
  "pulse": "Xung",
  "layer_settings": "Thiết lập Lớp",
  "viz_layer": "Lớp Trực quan hóa",
  "display_field": "Hiển thị Trường",
  "add_field": "Thêm Trường Trực quan hóa",
  "field": "Trường",
  "label": "Nhãn",
  "actions": "Các hành động",
  "no_layers": " Không có lớp khả dụng trong web scene được chọn.",
  "viz_not_supported": "Không hỗ trợ loại hình học của lớp được chọn."
});