define({
  "viz_settings": "Görselleştirme Ayarları",
  "viz_type": "Görselleştirme Türü",
  "max_height": "Maks Simge Yüksekliği (metre)",
  "max_width": "Maks Simge Genişliği (metre)",
  "interval": "Aralık (mili saniye)",
  "show_percent": "Değerleri tüm değerlerin yüzdesi olarak göster",
  "show_percentage_limited": "Kayıt sayısı 400'den büyük olduğu için bu özellik devre dışıdır.",
  "cycle_colors": "Renkleri Otomatik Değiştir",
  "area_extrusion": "Alan Uzatma",
  "bounce": "Geri Dönüş",
  "fireball": "Ateş Topu",
  "grid_surface": " Kılavuz Yüzeyi",
  "jet_trail": "Jet İzi",
  "point_extrusion": "Nokta Uzatma",
  "pulse": "Darbe",
  "layer_settings": "Katman Ayarları",
  "viz_layer": "Görselleştirme Katmanı",
  "display_field": "Alan Görüntüle",
  "add_field": "Görselleştirme Alanı Ekle",
  "field": "Alan",
  "label": "Etiket",
  "actions": "İşlemler",
  "no_layers": " Seçilen web görünümünde katman yok.",
  "viz_not_supported": "Seçili katmanın geometri türü için desteklenmiyor."
});