define({
  "viz_settings": "Pengaturan Visualisasi",
  "viz_type": "Tipe Visualisasi",
  "max_height": "Tinggi Simbol Maks (meter)",
  "max_width": "Lebar Simbol Maks (meter)",
  "interval": "Interval (milidetik)",
  "show_percent": "Perlihatkan nilai sebagai persentase semua nilai",
  "show_percentage_limited": "Ini dinonaktifkan karena jumlah record lebih besar dari 400.",
  "cycle_colors": "Ubah Warna Secara Otomatis",
  "area_extrusion": "Ekstrusi Area",
  "bounce": "Bounce",
  "fireball": "Fireball",
  "grid_surface": " Grid Surface",
  "jet_trail": "Jet Trail",
  "point_extrusion": "Point Extrusion",
  "pulse": "Pulse",
  "layer_settings": "Pengaturan Layer",
  "viz_layer": "Layer Visualisasi",
  "display_field": "Tampilkan Kolom",
  "add_field": "Tambahkan Kolom Visualisasi",
  "field": "Kolom",
  "label": "Label",
  "actions": "Tindakan",
  "no_layers": " Tidak tersedia layer pada web scene terpilih.",
  "viz_not_supported": "Tidak didukung untuk jenis geometri dari layer terpilih."
});